repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=200, --target-version=py37]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args:
          [
            --warn-unused-configs,
            --ignore-missing-imports,
            --disallow-untyped-defs,
            --follow-imports=silent,
            --install-types,
            --non-interactive,
          ]

      # - id: tests
      #   # stages: [push]
      #   name: Run tests
      #   entry: "poetry run pytest -v tests/"
      #   language: system
      #   verbose: true
