version: "3.7"

services:
  app:
      build: # "context" and "dockerfile" fields have to be under "build"
        context: .
        dockerfile: ./docker/Dockerfile
      command: "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
      tty: true
      hostname: app
      container_name: app
      volumes:
        - ../app/:/usr/src/app/
      ports:
        - 8000:8000
      env_file: 
        - .env.dev
      # depends_on:
      #   - db
      # restart: always 

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017-27019:27017-27019"