"""empty message

Revision ID: 6199751722dd
Revises: ef6a9ad9dc3e
Create Date: 2024-09-25 18:30:37.759025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6199751722dd'
down_revision: Union[str, None] = 'ef6a9ad9dc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_note_tag', 'note_tag_association', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_note_tag', 'note_tag_association', ['note_id', 'tag_id'])
    # ### end Alembic commands ###
